### ISSUE TITLE
Bad file descriptor only when EbpfLogger::init is called

### ISSUE THREAD

**Issue by drosseau-ivision** [aya-rs/aya#1324]
I'm learning Aya by writing a tracepoint that will look for calls to `execve` and just log some information about the call. I have the following:

```rust
#[tracepoint]
pub fn sys_enter_execve(ctx: TracePointContext) -> u32 {
    let pidtgid = helpers::bpf_get_current_pid_tgid();
    let pid = pidtgid as u32;
    let tgid = (pidtgid >> 32) as u32;
    let comm = match helpers::bpf_get_current_comm() {
        Ok(v) => v,
        Err(_) => [0u8; 16usize],
    };

    let mut idx = 0;
    for b in comm {
        if b == 0u8 {
            break;
        }
        idx += 1;
    }

    let comm_str = unsafe { core::str::from_utf8_unchecked(&comm[0..idx]) };
    info!(
        &ctx,
        "execve(): pid={}, tgid={}, comm={}", pid, tgid, comm_str
    );
    0
}
```

When I try to run it with my userspace program:

```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    TermLogger::init(
        LevelFilter::Debug,
        ConfigBuilder::new()
            .set_time_level(LevelFilter::Off)
            .set_thread_level(LevelFilter::Off)
            .set_target_level(LevelFilter::Off)
            .set_location_level(LevelFilter::Off)
            .build(),
        TerminalMode::Stderr,
        ColorChoice::Auto,
    )?;

    let mut bpf = Ebpf::load(aya::include_bytes_aligned!(concat!(
        env!("OUT_DIR"),
        "/ebpf-execve"
    )))?;

    EbpfLogger::init(&mut bpf)?;

    let prog: &mut TracePoint = bpf
        .program_mut("sys_enter_execve")
        .ok_or_else(|| anyhow::Error::msg("failed to get program"))?
        .try_into()
        .context("converting the program to a TracePoint")?;
    prog.load().context("loading")?;
    prog.attach("syscalls", "sys_enter_execve")
        .context("attaching")?;

    eprintln!("Waiting for Ctrl-C...");
    signal::ctrl_c().await?;
    eprintln!("Exiting...");

    Ok(())
}
```

I get:

```
Error: loading

Caused by:
    0: the BPF_PROG_LOAD syscall failed. Verifier output: fd 12 is not pointing to valid bpf_map
       verification time 38 usec
       stack depth 0+0+0+0+0
       processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

    1: Bad file descriptor (os error 9)
```

But if I comment out the `EbpfLogger::init(&mut bpf)?` I don't get that error and the program runs just fine.

```
uname -r -v -m
6.15.9-101.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Aug  2 12:38:24 UTC 2025 x86_64
```

Running on Fedora.

**Comment by tamird** [comment]
Yes logging is broken until we cut the next release. Discussion in #1294.

**Comment by addisoncrump** [comment]
At which commit did it stop working? This is really making debugging difficult 🙃

**Comment by freddyb** [comment]
Should this be fixed in the main branch since #1294 merged?

**Comment by tamird** [comment]
Yes. I think @vadorovsky is planning to cut a release.

**Comment by thomaseizinger** [comment]
I am pointing at latest `main` but still get the same error.

**Comment by tamird** [comment]
I am confused about this issue. The OP's code calls init but never actually "pumps" the logging machinery. 

@thomaseizinger please provide more complete information about what you're doing.

**Comment by thomaseizinger** [comment]
> [@thomaseizinger](https://github.com/thomaseizinger) please provide more complete information about what you're doing.

I am updating our `aya` dependency from 630a76711701a2f489f41d9d91076cc9bebb2675 to 30182463bdb6cce592477e66659d5f66f846cfcf in https://github.com/firezone/firezone/pull/10424. I've resolved the compile errors around the changes to the logging infra and the removal of `AsyncPerfEventArray`. I couldn't find any other migration instructions. The code compiles now but as you can see from the CI checks, it no longer starts.

This is all working code on the current commit (630a76711701a2f489f41d9d91076cc9bebb2675).

**Comment by tamird** [comment]
There are a lot of different CI checks. Where do I see a specific detailed failure?

**Comment by tamird** [comment]
Also your code has the same problem as OP's. You are not actually consuming the logs. For posterity your `init` call is here: https://github.com/firezone/firezone/blob/683a190855509df8776f3ff8d37cc638dc272e8c/rust/relay/server/src/ebpf/linux.rs#L47 but you drop the returned `Logger` which is almost certainly what's leading to your (and OP's) problems. See https://github.com/aya-rs/aya/tree/main/aya-log#user-space-code. With that, closing this. Please let me know if this doesn't solve the problem.

**Comment by thomaseizinger** [comment]
> drop the returned `Logger` which is almost certainly what's leading to your (and OP's) problems

Ah thanks for the pointer! It may be worth adding some more documentation to the [CHANGELOG](https://github.com/aya-rs/aya/blob/main/aya-log/CHANGELOG.md). The logger worked fine before the update.

If the logger isn't mean to be dropped, maybe it should have a `must_use`? That would lead to compiler warnings in that case and let users know they are doing something wrong.

**Comment by tamird** [comment]
I'm pretty sure your code's `let _ =` defeats `#[must_use]` but yeah it'd be good to add. Would you like to send a PR?

**Comment by thomaseizinger** [comment]
> I'm pretty sure your code's `let _ =` defeats `#[must_use]` but yeah it'd be good to add.

That is true yeah. This is an unfortunate migration because it follows the previous recommendation (AFAIK) where the logger could fail to initialise if there weren't any log statements at all in the eBPF code and hence to be robust, we completely discard the result.

> Would you like to send a PR?

Happy to. What would you like the `must_use` message to say?

**Comment by tamird** [comment]
Something sensible. You know the consequences of misuse now.

**Comment by thomaseizinger** [comment]
https://github.com/aya-rs/aya/pull/1350

Let me know what you think!
